apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: default
  releaseName: nginx

  chart:
    spec:
      chart: nginx
      version: "15.15.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system

  upgrade:
    remediation:
      retries: 3
      strategy: uninstall

  install:
    remediation:
      retries: 3

  values:
    replicaCount: 3
    service:
      type: NodePort

