apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: default
  releaseName: nginx
  chart:
    spec:
      chart: ./apps/nginx/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
